apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference
  labels:
    app: inference
    app.kubernetes.io/name: inference
    app.kubernetes.io/part-of: we-churn
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
        app.kubernetes.io/name: inference
        app.kubernetes.io/part-of: we-churn
    spec:
      containers:
        - name: inference
          image: omarraslan99/we-churn-inference:v0.1.0-seance3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: PREPROCESSING_URL
              value: http://preprocessing-svc:8001
            - name: MONITORING_URL
              value: http://monitoring-svc:8002
            - name: MODEL_DIR
              value: /app/models
            - name: CHURN_THRESHOLD
              value: "0.5"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
          command:
            - gunicorn
            - "services.inference.app:app"
            - "-k"
            - "uvicorn.workers.UvicornWorker"
            - "--bind"
            - "0.0.0.0:8000"
            - "--workers"
            - "4"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "704Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: inference-svc
  labels:
    app: inference
    app.kubernetes.io/name: inference
    app.kubernetes.io/part-of: we-churn
spec:
  type: NodePort
  selector:
    app: inference
  ports:
    - name: http
      port: 8000
      targetPort: 8000