apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocessing
  labels:
    app: preprocessing
    app.kubernetes.io/name: preprocessing
    app.kubernetes.io/part-of: we-churn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preprocessing
  template:
    metadata:
      labels:
        app: preprocessing
        app.kubernetes.io/name: preprocessing
        app.kubernetes.io/part-of: we-churn
    spec:
      containers:
        - name: preprocessing
          image: omarraslan99/we-churn-preprocessing:v1.0-seance5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
              name: http
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "300m"
              memory: "192Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: preprocessing-svc
  labels:
    app: preprocessing
    app.kubernetes.io/name: preprocessing
    app.kubernetes.io/part-of: we-churn
spec:
  type: ClusterIP
  selector:
    app: preprocessing
  ports:
    - name: http
      port: 8001
      targetPort: 8001